### ISSUE TITLE
Getting an error in VTO widget.

### ISSUE THREAD

**Issue by mudzz174** [jeeliz/jeelizGlassesVTOWidget#10]
I was trying to implement VTO for my website but facing as issue as
![image](https://user-images.githubusercontent.com/48759407/54686294-f317f580-4b3e-11e9-9500-83e5e3fee014.png)
I referred this [https://jeeliz.com/blog/vto-studio-lite-tutorial/](url) link to do so. My custom VTO js file is https://transfernow.net/235ca8e8wigz .
I used this html code
`<!DOCTYPE html><html>
    <meta charset='utf-8'>
    <head>
        <title>MY VTO WIDGET</title><script type="text/javascript" src="/webcam/jeeliz/jeelizGlasses/JeelizWidgetVTO.js"></script>
    </head>
    <body>
        <canvas width="800" height="600" id="jeelizWidgetVTOCanvas"></canvas><button onclick="VTOStudio.main()">Click to start the widget</button>
    </body></html>`

**Comment by xavierjs** [comment]
https://jeeliz.com/blog/vto-studio-lite-tutorial/ does not use this github project, it is based on Jeeliz FaceFilter: https://github.com/jeeliz/jeelizFaceFilter
You have 404 errors because of missing dependancies. They are all included in the FaceFilter repo.
I close the issue since it is not related to this github project but to FaceFilter.
