### ISSUE TITLE
Integration with nextjs

### ISSUE THREAD

**Issue by tausif-fardin** [jeeliz/jeelizGlassesVTOWidget#49]
`import { JEELIZVTO, JEELIZVTOWIDGET } from 'jeelizvtowidget';`

`SyntaxError: Cannot use import statement outside a module getting this error while importing.`

Added the jeelizvtowidget as dev-dependencies still getting the same error.
Also getting this warning in vscode `Could not find a declaration file for module 'jeelizvtowidget'.`

**Comment by xavierjs** [comment]
You need to disable SSR for this lib, as explained in this issue (for a similar lib, Jeeliz FaceFilter): https://github.com/jeeliz/jeelizFaceFilter/issues/283

If you still need help integrating it with NextJS, I provide development services to help with integration. Please contact me at contact@jeeliz.com and provide your company details so that I can send you the SA proposal.

**Comment by tausif-fardin** [comment]
Umm i don't think so, 
![image](https://user-images.githubusercontent.com/58599676/219271654-7d0b9f77-50ad-4a4e-95b1-7d4a20429861.png)
Couldn't find the module!

**Comment by xavierjs** [comment]
Hey pal, this is the issue section of Jeeliz VTO widget.
Not a support board for basic questions about Typescript, NextJS or NPM. You can find your answers quite easily here: https://stackoverflow.com/ or there: https://www.google.com/
If you need help with that, contact me by email and I will provide paid support. But your issue is really not related to Jeeliz VTO widget. I close this issue for this reason.
