### ISSUE TITLE
Conflicts with jQuery

### ISSUE THREAD

**Issue by azkdev** [jeeliz/jeelizGlassesVTOWidget#5]
Hi there,
Is this plugin compatible with jQuery 100%?
Cause when i'm trying to create plugin to the page, i got this error:

![image](https://user-images.githubusercontent.com/21266851/49376164-0bd6d980-f70f-11e8-977c-6efade3fae4c.png)

Waiting for your feedback, as soon as possible )
Thanks, 
Alexandru

**Comment by xavierjs** [comment]
Hi,

There is no conflict with JQuery, it is more some protection Jquery is adding the control the DOM modifications.
I think this may solve your problem: https://webkul.com/blog/how-to-override-javascript-jquery-functions-and-events/
Since it is not directly related with a Jeeliz lib or product, we can help you to integrate the plugin but we charge for this. You can send an email to contact__at__jeeliz.com for more informations.

Best,
Xavier

**Comment by azkdev** [comment]
Thank you. 

It helps me.
